//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasE()
        {
            this.DetalleFactura = new HashSet<DetalleFacturaE>();
        }
    
        public int FacturaID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
    
        public virtual ClientesE Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaE> DetalleFactura { get; set; }
    }
}
