//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSepareE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanSepareE()
        {
            this.DetallePlanSepareXProducto = new HashSet<DetallePlanSepareXProductoE>();
        }
    
        public int PlanSepareID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime FechaSepare { get; set; }
        public decimal TotalPrecioSepare { get; set; }
        public decimal ValorMinimo { get; set; }
    
        public virtual ClientesE Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePlanSepareXProductoE> DetallePlanSepareXProducto { get; set; }
    }
}
